# RUN COMMAND
# docker-compose -f docker-compose.yaml build
# docker-compose -f docker-compose.yaml up
# docker-compose -f docker-compose.yaml up -d
# docker-compose -f docker-compose.yaml start
# docker-compose -f docker-compose.yaml stop
# docker-compose -f docker-compose.yaml logs -f

# Docker-compose reference: https://docs.docker.com/compose/compose-file/


version: '3'

services:
   
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    env_file:
      - .db.env
    networks:
      - wordpress


  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
    env_file:
      - .wordpress.env
    networks:
      - wordpress


  # DOCKER HUB: https://hub.docker.com/r/phpmyadmin/phpmyadmin/
  # USERNAME: root
  # PASSWORD: MYSQL_ROOT_PASSWORD
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8090:80'
    environment:
      - PMA_HOST=db
    env_file:
      - .phpmyadmin.env
    networks:
      - wordpress



volumes:
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker/wordpress/data

  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker/db/data



networks:
  wordpress:
    driver: bridge
